name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Clean up artifacts
      run: cargo clean
    
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: ClementTsang/cargo-action@v0.0.2
      with:
        command: build
        args: --release --target aarch64-unknown-linux-musl
        use-cross: true
        cross-version: 0.2.4
    
    - name: Hash bin
      run: sha256sum target/aarch64-unknown-linux-musl/release/bookmark-bot > sha256sum.txt
    
    - name: TarBall it 
      run: |
        mkdir release && \
        mv target/aarch64-unknown-linux-musl/release/bookmark-bot LICENSE README.md .env.example bookmark-bot.service release && \
        cp sha256sum.txt release && \
        tar -czf release.tar.gz 
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          sha256sum.txt
          release.tar.gz
