name: Rust

on:
  push:
    branches: [ "master", "pull" ]
  pull_request:
    branches: [ "master", "pull" ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release

    - uses: actions/upload-artifact@v3
      with:
        name: bookmark-bot
        path: target/release/bookmark-bot
